### ISSUE TITLE
Chrome Installation

### ISSUE THREAD

**Issue by purva06** [hypery2k/galenframework-cli#129]
Hi ,

We are using galenframework/cli image for running galen.

When I run my galen command it give me below error also it is not installing google-chrome in usr/lib it is only installing Firefox.

Sep 17, 2019 1:22:23 PM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using `new ChromeOptions()` is preferred to `DesiredCapabilities.chrome()`
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: The driver executable does not exist: /usr/lib/google-chrome
	at com.galenframework.GalenMain.execute(GalenMain.java:60)
	at com.galenframework.GalenMain.main(GalenMain.java:78)
Caused by: java.lang.IllegalStateException: The driver executable does not exist: /usr/lib/google-chrome
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:132)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:156)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:91)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:147)
	at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:103)
	at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:94)
	at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:70)
	at com.galenframework.actions.GalenActionDump.execute(GalenActionDump.java:39)
	at com.galenframework.GalenMain.execute(GalenMain.java:58)
	... 1 more

Please suggest.

**Comment by hypery2k** [comment]
Could you provide details about your setup? os version, package version, chrome version etc ...
