### ISSUE TITLE
NPM Install is failing

### ISSUE THREAD

**Issue by alwinmark** [hypery2k/galenframework-cli#17]
Since today npm install of galenframework-cli is not working anymore

Console output for `npm install galenframework-cli
```Running at platform: linux
Download already available at /tmp/galenframework/galen-bin-2.1.3.zip
Extracting zip contents
Removing /tmp/node_modules/galenframework-cli/node_modules/galenframework/lib/galen
Copying extracted folder /tmp/galenframework/galen-bin-2.1.3.zip-extract-1448273707256/galen-bin-2.1.3 -> /tmp/node_modules/galenframework-cli/node_modules/galenframework/lib/galen
Writing location.js file
Done. galen binary available at  /tmp/node_modules/galenframework-cli/node_modules/galenframework/lib

> galenframework-cli@2.1.3 install /tmp/node_modules/galenframework-cli
> node install.js

Galen installation failed [Error: not found: galen] Error: not found: galen
    at F (/tmp/node_modules/galenframework-cli/node_modules/which/which.js:78:19)
    at E (/tmp/node_modules/galenframework-cli/node_modules/which/which.js:82:29)
    at /tmp/node_modules/galenframework-cli/node_modules/which/which.js:93:16
    at Object.oncomplete (fs.js:107:15)
npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "galenframework-cli"
npm ERR! node v0.10.2
npm ERR! npm  v2.8.4
npm ERR! code ELIFECYCLE

npm ERR! galenframework-cli@2.1.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the galenframework-cli@2.1.3 install script 'node install.js'.
npm ERR! This is most likely a problem with the galenframework-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls galenframework-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/npm-debug.log
```

npm-debug.log
```
13203 verbose unlock done using /home/alwin/.npm/_locks/galenframework-cli-f9601f1bb8fb2270.lock for /home/alwin/git/shop-prototype/node_modules/galenframework-cli
13204 verbose stack Error: galenframework-cli@2.1.3 install: `node install.js`
13204 verbose stack Exit status 1
13204 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
13204 verbose stack     at EventEmitter.emit (events.js:98:17)
13204 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
13204 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
13204 verbose stack     at maybeClose (child_process.js:703:16)
13204 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:770:5)
13205 verbose pkgid galenframework-cli@2.1.3
13206 verbose cwd /home/alwin/git/shop-prototype
13207 error Linux 3.13.0-68-generic
13208 error argv "node" "/usr/local/bin/npm" "install"
13209 error node v0.10.2
13210 error npm  v2.8.4
13211 error code ELIFECYCLE
13212 error galenframework-cli@2.1.3 install: `node install.js`
13212 error Exit status 1
13213 error Failed at the galenframework-cli@2.1.3 install script 'node install.js'.
13213 error This is most likely a problem with the galenframework-cli package,
13213 error not with npm itself.
13213 error Tell the author that this fails on your system:
13213 error     node install.js
13213 error You can get their info via:
13213 error     npm owner ls galenframework-cli
13213 error There is likely additional logging output above.
13214 verbose exit [ 1, true ]
```

I'll try to solve this problem also on my own, if I've any updates I'll let you know.

**Comment by hypery2k** [comment]
first you didn't install it globally, e.g. `npm install -g galenframework-cli`
Do you want to use it in the command line or just in a local node build?

**Comment by alwinmark** [comment]
Yes, I want it to be executed on a ci. To define the version in my Package I use a local installation. So I've this line in my package.json:
```
    "galenframework-cli": "^2.0.7",
```

**Comment by alwinmark** [comment]
Version 2.1.2 is still working as expected only 2.1.3 is broken (from my point of view)

**Comment by hypery2k** [comment]
you can use galenframework (without -cli). This just download the Galen jar for local run, see https://www.npmjs.com/package/galenframework

**Comment by alwinmark** [comment]
Thanks. It seems to be fixed, I've just to wait until the ci runs threw correctly, but I think that was the issue

**Comment by hypery2k** [comment]
the basic idea of the split was to make a small core module which just downloads the galen jar and one which eases the command line integration with autocompletion and driver installation
