### ISSUE TITLE
Windows Chrome Driver error

### ISSUE THREAD

**Issue by hypery2k** [hypery2k/galenframework-cli#20]
For windows you currently get an error:

```
Error:Cannot run program "..\chromedriver" (in directory "."); createProcess error=193, %1 is not a valid win32 application.
```

**Comment by hypery2k** [comment]
see https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/galen-framework/VdnKwaCiePI

**Comment by ritdhwaj** [comment]
I am still getting this same error on windows my package.json file looks like this 
```
`{
  "name": "galen-framework",
  "version": "1.0.0",
  "description": " Responsive Design Tests",
  "main": "index.js",
  "scripts": {
    "galen": "galen test tests/base_test.test.js --htmlreport ./tests/visual/reports/"
  },
  "devDependencies": {
    "galenframework": "2.3.3",
    "chromedriver": "2.35",
    "geckodriver": ""
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/ritdhwaj/galen-framework.git"
  },
  "keywords": [
    "galen",
    "framework"
  ],
  "author": "Ritdhwaj Singh Chandel",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/ritdhwaj/galen-framework/issues"
  },
  "homepage": "https://github.com/ritdhwaj/galen-framework#readme"
}`
```
 error received 

```
========================================
Test: Home page
========================================
Mar 18, 2018 8:02:04 PM org.openqa.selenium.os.UnixProcess checkForError
SEVERE: org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "C:\Users\Rithdwaj Singh Chand\Desktop\galentests\node_modules\.bin\chromedriver" (in directory "."): CreateProcess error=193, %1 is not a valid Win32 application)
org.mozilla.javascript.WrappedException: Wrapped org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'GGN000162407001', ip: '10.104.68.168', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: ChromeDriver (<cmd>#37)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
        at org.mozilla.javascript.gen._cmd__18._c_createDriver_2(<cmd>:37)
        at org.mozilla.javascript.gen._cmd__18.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen.C__Users_Rithdwaj_Singh_Chand_Desktop_galentests_tests_base_test_test_js_20._c_anonymous_1(C:\Users\Rithdwaj Singh Chand\Desktop\galentests\tests\base_test.test.js:2)
        at org.mozilla.javascript.gen.C__Users_Rithdwaj_Singh_Chand_Desktop_galentests_tests_base_test_test_js_20.call(C:\Users\Rithdwaj Singh Chand\Desktop\galentests\tests\base_test.test.js)
        at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2429)
        at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen._cmd__17._c_invokeFunc_2(<cmd>:31)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
        at org.mozilla.javascript.gen._cmd__17._c_anonymous_22(<cmd>:280)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3090)
        at org.mozilla.javascript.gen._cmd__17.call(<cmd>)
        at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:606)
        at org.mozilla.javascript.JavaAdapter.access$000(JavaAdapter.java:15)
        at org.mozilla.javascript.JavaAdapter$1.run(JavaAdapter.java:586)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:583)
        at adapter1.execute(<adapter>)
        at com.galenframework.TestRunnable.runTest(TestRunnable.java:75)
        at com.galenframework.TestRunnable.run(TestRunnable.java:101)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'GGN000162407001', ip: '10.104.68.168', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_161'
Driver info: driver.version: ChromeDriver
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:180)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:168)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:78)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:178)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:146)
        at com.galenframework.browser.SeleniumBrowserFactory.getDriver(SeleniumBrowserFactory.java:98)
        at com.galenframework.browser.SeleniumBrowserFactory.createLocalBrowser(SeleniumBrowserFactory.java:89)
        at com.galenframework.browser.SeleniumBrowserFactory.openBrowser(SeleniumBrowserFactory.java:65)
        at com.galenframework.utils.GalenUtils.createDriver(GalenUtils.java:265)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        ... 31 more
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:40782/status] to be available after 20002 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:107)
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:177)
        ... 48 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:140)
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:80)
        ... 49 more
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:128)
        ... 50 more

========================================
----------------------------------------
========================================
Failed tests:
    Home page

Suite status: FAIL
Total tests: 1
Total failed tests: 1
Total failures: 1
There were failures in galen tests
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! galen-framework@1.0.0 galen: `galen test tests/base_test.test.js --htmlreport ./tests/visual/reports/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the galen-framework@1.0.0 galen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rithdwaj Singh Chand\AppData\Roaming\npm-cache\_logs\2018-03-18T14_32_04_526Z-debug.log
```

Any quick help is appreciated.

**Comment by hypery2k** [comment]
you're receiving a timeout error, so it has nothing to do with the driver itself.

Basically Galen is giving up as you're page simply isn't loading in a reasonable time.
