### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by arkroy** [hypery2k/galenframework-cli#26]
NPM Install not working. Please could you help. Attached npm-debug-log. Error on console below:

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "galenframework-cli"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! galenframework-cli@2.2.3 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the galenframework-cli@2.2.3 install script 'node install.js'.
npm ERR! This is most likely a problem with the galenframework-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls galenframework-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ark/Desktop/FT_BuildAutomation/fti_corp/npm-debug.log

[npm-debug.log.zip](https://github.com/hypery2k/galenframework-cli/files/180017/npm-debug.log.zip)

**Comment by hypery2k** [comment]
Can you please install the package globally with 'npm install -g'. The cli module is intented for system wide usage and the core module for build integration, see https://github.com/hypery2k/galenframework-cli/blob/master/README.md

**Comment by arkroy** [comment]
Yes, both npms galenframework and galenframework-cli are already installed as well as locally and globally

**Comment by hypery2k** [comment]
So you are trying to update them?

**Comment by arkroy** [comment]
I have updated both with fresh installs, but it throws and error galen not found. The galen framework seems to be working if I run it direclty through the terminal instead of gulp.

**Comment by hypery2k** [comment]
can you try to install it with 'sudo npm install -g galenframework-cli' ?

**Comment by arkroy** [comment]
Yup, installed both gallen and gallenframework-cli gobally with sudo. The error poping up: 
Error: Could not start galen. Galen (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/lib/../node_modules/galenframework/bin/galen.cmd) not found?
Arks-MacBook-Air:fti_corp ark$

**Comment by hypery2k** [comment]
works perfectly for me, but you can try the latest develop branch`
`
npm install galenframework-cli@2.3.0-beta.0
`

**Comment by arkroy** [comment]
Thanks, seems the error changed (below)
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at runGalen (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/lib/gulp-galen.js:49:21)
    at DestroyableTransform._transform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/lib/gulp-galen.js:110:4)
    at DestroyableTransform.Transform._read (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp-galenframework/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/ark/Desktop/FT_BuildAutomation/fti_corp/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)

**Comment by arkroy** [comment]
@hypery2k : Thanks for your help on this, however due timeline issues I have chosen to go with galen usage as described here: http://galenframework.com/docs/tutorial-using-galen-with-a-task-runner/. I wouldn't like to pursue this issue further.

Thanks again for your time and effort to support me on this.
