### ISSUE TITLE
Unable to install in local space

### ISSUE THREAD

**Issue by MichaelKunze** [hypery2k/galenframework-cli#44]
`npm install galenframework-cli`

```
> chromedriver@2.28.0 install /home/mikunze/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Receiving...
Received 782K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3377K total.
Extracting zip contents
Copying to target path /home/mikunze/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/mikunze/node_modules/chromedriver/lib/chromedriver/chromedriver

> galenframework@2.3.3 install /home/mikunze/node_modules/galenframework-cli/node_modules/galenframework
> node install.js

info Running at platform: linux 
info Downloading https://github.com/galenframework/galen/releases/download//galen-2.3.3/galen-bin-2.3.3.zip
info Saving to /tmp/galenframework/galen-bin-2.3.3.zip
info Receiving... 
  [======================================--] 96% 0.0sinfo 
info Received 19314K total. 
info Extracting zip contents 
info Removing /home/mikunze/node_modules/galenframework-cli/node_modules/galenframework/lib/galen
info Copying extracted folder /tmp/galenframework/galen-bin-2.3.3.zip-extract-1495184075529/galen-bin-2.3.3 -> /home/mikunze/node_modules/galenframework-cli/node_modules/galenframework/lib/galen
info Writing location.js file 
info Done. galen binary available at  /home/mikunze/node_modules/galenframework-cli/node_modules/galenframework/lib
info Modified files: /home/mikunze/node_modules/galenframework-cli/node_modules/galenframework/lib/galen/galen.bat

> galenframework-cli@2.3.3 install /home/mikunze/node_modules/galenframework-cli
> node install.js

ERR! Galen installation failed Error: not found: galen
ERR! Galen installation failed     at F (/home/mikunze/node_modules/which/which.js:78:19)
ERR! Galen installation failed     at E (/home/mikunze/node_modules/which/which.js:82:29)
ERR! Galen installation failed     at /home/mikunze/node_modules/which/which.js:93:16
ERR! Galen installation failed     at FSReqWrap.oncomplete (fs.js:82:15)
ERR! Galen installation failed  [Error: not found: galen] Error: not found: galen
ERR! Galen installation failed     at F (/home/mikunze/node_modules/which/which.js:78:19)
ERR! Galen installation failed     at E (/home/mikunze/node_modules/which/which.js:82:29)
ERR! Galen installation failed     at /home/mikunze/node_modules/which/which.js:93:16
ERR! Galen installation failed     at FSReqWrap.oncomplete (fs.js:82:15)
```

Happend on Ubuntu LTS 16.04

**Comment by hypery2k** [comment]
which node version you're using?
Please post the output of `node --version && npm --version`

**Comment by DieMaske** [comment]
v7.8.0
4.2.0

**Comment by hypery2k** [comment]
can you give node 6 and npm 3 a try as it's the LTS version and maybe some things broken with node 7

I'm not able to reproduce you error with node 7

**Comment by DieMaske** [comment]
The problem persists even with node 6 and npm 3. We found out that a local installation will only work when you have galenframework-cli globally installed. But if galenframework-cli is not installed globally on the system the above error will occur regardless of which version of node you use (we tested with node versions 4,6 and 7 all with the same error pattern).

**Comment by MichaelKunze** [comment]
Maybe some kind of permission problem?

**Comment by hypery2k** [comment]
could you try the latest snapshot? `galenframework-cli@2.3.3-develop-17`

**Comment by DieMaske** [comment]
It does work now! :+1:

**Comment by hypery2k** [comment]
and having a CI test for this. So the bugfix will be shipped with the next Galen version
