### ISSUE TITLE
npm install throws "cannot access parent directories: Permission denied"

### ISSUE THREAD

**Issue by p00j4** [hypery2k/galenframework-cli#5]
I had installed with sudo, still the issue exists, 
supporting logs-  https://github.com/galenframework/galen/issues/275#

Logs:
``` 
npm http 304 https://registry.npmjs.org/jsonpointer
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/get-stdin
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/is-property
/usr/local/bin/galen -> /usr/local/lib/node_modules/galenframework-cli/bin/galen
``` 
```bash
> galenframework-cli@1.6.3 install /usr/local/lib/node_modules/galenframework-cli
> node install.js
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:811
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:811:23)
    at startup (node.js:58:13)
    at node.js:902:3
npm ERR! galenframework-cli@1.6.3 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the galenframework-cli@1.6.3 install script.
npm ERR! This is most likely a problem with the galenframework-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls galenframework-cli
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "galenframework-cli"
npm ERR! cwd /Users/pooja
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pooja/npm-debug.log
npm ERR! not ok code 0
more info from , npm-debug.log

5557 info install galenframework-cli@1.6.3
5558 verbose unsafe-perm in lifecycle false
5559 info galenframework-cli@1.6.3 Failed to exec install script
5560 info /usr/local/lib/node_modules/galenframework-cli unbuild
5561 info preuninstall galenframework-cli@1.6.3
5562 info uninstall galenframework-cli@1.6.3
5563 verbose true,/usr/local/lib/node_modules,/usr/local/lib/node_modules unbuild galenframework-cli@1.6.3
5564 verbose /usr/local/bin,[object Object] binRoot
5565 info postuninstall galenframework-cli@1.6.3
5566 error galenframework-cli@1.6.3 install: `node install.js`
5566 error Exit status 8
5567 error Failed at the galenframework-cli@1.6.3 install script.
5567 error This is most likely a problem with the galenframework-cli package,
5567 error not with npm itself.
5567 error Tell the author that this fails on your system:
5567 error     node install.js
5567 error You can get their info via:
5567 error     npm owner ls galenframework-cli
5567 error There is likely additional logging output above.
5568 error System Darwin 13.4.0
5569 error command "node" "/usr/local/bin/npm" "install" "-g" "galenframework-cli"
5570 error cwd /Users/pooja
5571 error node -v v0.10.26
5572 error npm -v 1.4.3
5573 error code ELIFECYCLE
5574 verbose exit [ 1, true ]
```

**Comment by hypery2k** [comment]
You are using OS X right? Which version?

Did you used a previous version of the npm package?

**Comment by hypery2k** [comment]
works on OS X 10.9 and OS X 10.10 for me even with upgrades

**Comment by hypery2k** [comment]
As per photusenigma at: https://github.com/npm/npm/issues/4815

Run these commands in a terminal window (note - DON'T replace the $USER part...thats a linux command to get your user!):
```bash
sudo chown -R $USER ~/.npm
sudo chown -R $USER /usr/local/lib/node_modules
```
...and...if you're on a mac (like I am), and still see errors after running these commands, then run this last one and you should be good. (Recommend you try testing before you do this one. I don't like changing the permissions on the ENTIRE /usr/local directory unless it really seems necessary!)
```bash
sudo chown -R $USER /usr/local
```

**Comment by hypery2k** [comment]
any news?

**Comment by p00j4** [comment]
thanks @hypery2k , though even after trying chown, the error is same
I'm on OSx, 10.9.5, npm version-1.4.3
```
> galenframework-cli@1.6.3 install /usr/local/lib/node_modules/galenframework-cli
> node install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:811
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
```

the error, ideally suggests that, trying to access a directory which parent directory doesn't exist, for me it looks like a naming issue in the package, isn't it?

**Comment by hypery2k** [comment]
mmmh really strange, even within travis CI which uses OS X 10.9.5 this error is not occurring. Tested it with Linux, OS X and Windows.
I'll try to setup a OS X 10.9 VM. How did you installed NPM?

**Comment by p00j4** [comment]
using 'brew'

**Comment by hypery2k** [comment]
tried a stock OS X 9 VM installed brew, then node, then galenframework-cli and it worked
then try
```
sudo chown -R `whoami` /usr/lib/node_modules/
sudo chown -R myname ~/.npm/_locks
```

**Comment by hypery2k** [comment]
any news?

**Comment by hypery2k** [comment]
Closed due to no response

**Comment by p00j4** [comment]
@hypery2k : no luck, same error again
I also upgraded to Yosemite-10.10.3
looks like my npm having some issue! but I'm able to install any other project.
![image](https://cloud.githubusercontent.com/assets/6470509/7607781/d5781176-f981-11e4-8186-302955dc266d.png)

**Comment by hypery2k** [comment]
try this
```bash
sudo rm -r /usr/local/lib/node_modules/galenframework-cli
sudo npm install -g galenframework-cli
```

**Comment by hypery2k** [comment]
fixed in master, see #6

**Comment by JetQin** [comment]
I meet the same error, but when i change the ./npm owner, the errors are gone. my version is 
```
npm -v
3.3.12
```

**Comment by pnagar1705** [comment]
I am facing the same problem. I have OS X version 10.11.6 and npm is 5.6.0. I am trying to install angular cli via sudo npm install -g @angular/cli

**Comment by caozengzeng** [comment]
npm config set user 0 

npm config set unsafe-perm true

**Comment by mding5692** [comment]
> npm config set user 0
> 
> npm config set unsafe-perm true

Doing this worked for me, much thanks
