### ISSUE TITLE
installation issue on windows

### ISSUE THREAD

**Issue by ritdhwaj** [hypery2k/galenframework-cli#52]
when installing galen framework getting his issue on windows:
```
Downloading geckodriver... Extracting... Complete.

> galenframework-cli@2.3.6 postinstall C:\Users\Rithdwaj\AppData\Roaming\npm\node_modules\galenframework-cli
> node postinstall.js

info Install exited unexpectedly
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! galenframework-cli@2.3.6 postinstall: `node postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the galenframework-cli@2.3.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rithdwaj\AppData\Roaming\npm-cache\_logs\2018-04-15T19_30_11_617Z-debug.log

C:\Users\Rithdwaj>galen
module.js:540
    throw err;
    ^

Error: Cannot find module 'C:\Users\Rithdwaj Singh Chand\AppData\Roaming\npm\node_modules\galenframework-cli\bin\galen'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by hypery2k** [comment]
which node version you're using?

**Comment by ritdhwaj** [comment]
8.9.4

**Comment by hypery2k** [comment]
can you retry with 2.3.7?
